# Set update schedule for GitHub Actions
version: 2
updates:
    - package-ecosystem: "gomod"
      directory: "/"
      schedule:
          interval: "daily"
      allow:
          - dependency-type: "direct"
    - package-ecosystem: "npm"
      directory: "/ccc-client"
      schedule:
          interval: "daily"
      allow:
          - dependency-type: "direct"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
