# Set update schedule for GitHub Actions
# open-pull-requests-limit is set to 0 because we only want security updates and those override this limit
# see https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file
version: 2
updates:
    - package-ecosystem: "gomod"
      directory: "/"
      schedule:
          interval: "daily"
      allow:
          - dependency-type: "direct"
      open-pull-requests-limit: 0
    - package-ecosystem: "npm"
      directory: "/ccc-client"
      schedule:
          interval: "daily"
      allow:
          - dependency-type: "direct"
      open-pull-requests-limit: 0
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 0