overrides:
    - files:
          - "**/*.yaml"
          - "**/*.yml"
          - ".prettierrc*"
      options:
          parser: "yaml"
          tabWidth: 4
          useTabs: false
          printWidth: 120
