set SPACEFISH_PROMPT_SEPARATE_LINE false
set SPACEFISH_PROMPT_ADD_NEWLINE false

set SPACEFISH_PROMPT_ORDER exit_code dir char
set SPACEFISH_RPROMPT_ORDER kubecontext time

set SPACEFISH_CHAR_SUFFIX "  "

set SPACEFISH_KUBECONTEXT_PREFIX ""
set SPACEFISH_KUBECONTEXT_SYMBOL ""

set SPACEFISH_DIR_TRUNC_REPO false
set SPACEFISH_DIR_TRUNC 0

set SPACEFISH_TIME_SHOW true
set SPACEFISH_TIME_PREFIX ""
set SPACEFISH_TIME_SUFFIX ""
