version: "3"
services:
    cli:
        image: "ghcr.io/dodevops/cloudcontrol-aws:latest"
        ports:
            - "8080" # CloudControlCenter port
            - "8081" # Port that can be used for port forwardings
        environment:
            - "FEATURES=terraform:0.12.17 helm:2.16.1"
            - "AWS_ACCESS_KEY_ID"
            - "AWS_SECRET_ACCESS_KEY"
            - "AWS_DEFAULT_REGION"
            - "K8S_CLUSTERS=<resourcegroup:cluster,resourcegroup:cluster>"
