version: "3"
services:
    cli:
        image: "dodevops/cloudcontrol-tanzu:latest"
        volumes:
            - "<path-to-terraform>:/terraform"
        ports:
            - "8080" # CloudControlCenter port
            - "8081" # Port that can be used for port forwardings
        environment:
            - "USE_terraform=yes"
            - "USE_helm=yes"
            - "TERRAFORM_VERSION=0.12.17"
            - "HELM_VERSION=2.16.1"
            - "USE_kubernetes=yes"
            - "TANZU_HOST=tanzu.example.com"
            - "TANZU_USERNAME=myuser"
            - "KUBECTL_VSPHERE_PASSWORD=mysecret"
            - "TANZU_CLUSTERS=tanzu-namespace:my-cluster,tanzu-namespace2:my-second-cluster"
            - "TANZU_SKIP_TLS_VERIFY=yes"
