icon: "🐳"
title: "Kubernetes"
description: "Installs and configures [kubernetes](https://kubernetes.io/docs/reference/kubectl/overview/) with [kubectl](https://kubernetes.io/docs/reference/kubectl/overview/) to connect to the flavour's kubernetes clusters"
configuration:
    - |
        (azure flavour) Environment AZ_K8S_CLUSTERS: A comma separated list of AKS clusters to manage
        inside *CloudControl* (only for azure flavour).
        Each cluster is a pair of resource group and cluster name, separated by a colon. Optionally, you can specify
        the target subscription.
        For example: myresourcegroup:myk8s,myotherresourcegroup@othersubscription:mysecondk8s will install myk8s from
        the myresourcegroup resource group and mysecondk8s from the resource group myotherresourcegroup in the
        subscription othersubscription.
        Prefix a cluster name with an ! to load the admin-credentials for that cluster instead of the user credentials.
        This generates the script `k8s-relogin` which allows you to recreate the Kubernetes credentials.
    - |
        (azure flavour) Environment AZ_K8S_INSTALL_OPTIONS: Additional options for the az aks install-cli programm.
        (Defaults to empty)
    - |
        (aws flavour) Environment AWS_K8S_CLUSTERS: A comma separated list of EKS clusters to manage
        inside *CloudControl* (only for aws flavour).
        For each cluster give the cluster name. If you need to assume an ARN role, add that to the clustername
        with an additional | added.
        For example: myekscluster|arn:aws:iam::32487234892:sample/sample

        If you additionally need to assume a role before fetching the EKS credentials, add the role, prefixed with
        an @:
        myekscluster|arn:aws:iam::4327849324:sample/sample@arn:aws:iam::specialrole
    - |
        (aws flavour) Environment AWS_SKIP_GPG: If set, skips the gpg checks for the yum repo of kubectl,
        as [this](https://github.com/kubernetes/kubernetes/issues/37922)
        [sometimes](https://github.com/kubernetes/kubernetes/issues/60134)
        seems to fail.
    - |
        (simple and aws flavour) Environment KUBECTL_VERSION: The version of kubectl to install
    - |
        (tanzu flavour)
        * Environment TANZU_HOST: The tanzu host to download the kubectl vsphere plugin from and authenticate against
        * Environment TANZU_USERNAME: The username to authenticate with
        * Environment KUBECTL_VSPHERE_PASSWORD: The password to authenticate with
        * Environment TANZU_CLUSTERS: A comma separated list of namespace:cluster name pairs
        * Environment TANZU_ADD_CONTROL_CLUSTER: Whether to also authenticate against the control cluster [false]
        * Environment TANZU_SKIP_TLS_VERIFY: Skip TLS verification [false]
        * Environment TANZU_VSPHERE_PLUGIN_PATH: The path where to find the kubectl vsphere plugin [/wcp/plugin/linux-amd64/vsphere-plugin.zip]
        
        This generates the script `k8s-relogin` which allows you to recreate the Kubernetes credentials.
