title: "🐳 [kubernetes](https://kubernetes.io/docs/reference/kubectl/overview/)"
description: "Installs and configures [kubectl](https://kubernetes.io/docs/reference/kubectl/overview/) to connect to the flavour's kubernetes clusters"
configuration:
    - |
        (azure flavour) Environment AZ_K8S_CLUSTERS: A comma separated list of AKS clusters to manage
        inside *CloudControl* (only for azure flavour).
        Each cluster is a pair of resource group and cluster name, separated by a colon.
        For example: myresourcegroup:myk8s,myotherresourcegroup:mysecondk8s will install myk8s from
        the myresourcegroup resource group and mysecondk8s from the resource group myotherresourcegroup.
        Prefix a cluster name with an ! to load the admin-credentials for that cluster instead of the user credentials.
    - |
        (aws flavour) Environment AWS_K8S_CLUSTERS: A comma separated list of EKS clusters to manage
        inside *CloudControl* (only for aws flavour).
        For each cluster give the cluster name. If you need to assume an ARN role, add that to the clustername
        with an additional | added.
        For example: myekscluster|arn:aws:iam::32487234892:sample/sample

        If you additionally need to assume a role before fetching the EKS credentials, add the role, prefixed with
        an @:
        myekscluster|arn:aws:iam::4327849324:sample/sample@arn:aws:iam::specialrole

