version: "3"
services:
    cli:
        image: "dodevops/cloudcontrol-simple:latest"
        volumes:
            - "<path-to-terraform>:/terraform"
        ports:
            - "8080" # CloudControlCenter port
            - "8081" # Port that can be used for port forwardings
        environment:
            - "USE_terraform=yes"
            - "USE_helm=yes"
            - "TERRAFORM_VERSION=0.12.17"
            - "HELM_VERSION=2.16.1"
