version: "3"
services:
    cli:
        image: "ghcr.io/dodevops/cloudcontrol-azure:latest"
        platform: "linux/amd64"
        ports:
            - "8080" # CloudControlCenter port
            - "8081" # Port that can be used for port forwardings
        environment:
            - "FEATURES=terraform:0.12.17 helm:2.16.1"
            - "AZ_SUBSCRIPTION=<subscription>"
            - "K8S_CLUSTERS=<resourcegroup:cluster,resourcegroup:cluster>"
