name: "Build and push"

on:
    push:
        branches:
            - master
    release:
        types:
            - created

jobs:
    init:
        steps:
            -   name: Set tag to latest
                uses: allenevans/set-env@v1.0.0
                with:
                    TAG: latest
                if: github.ref == "master"
            -   name: Set tag to release
                uses: allenevans/set-env@v1.0.0
                with:
                    TAG: ${{ github.ref }}
                if: github.ref != "master"
    build:
        steps:
            -   name: Checkout
                uses: actions/checkout@v1
            -   run: build.sh $TAG
    push:
        -   name: Push AWS Image
            uses: julioarruda/pushimagetoregistry@v1
            with:
                acr-tokenname: ${{ secrets.DOCKER_USERNAME }}
                acr-token: ${{ secrets.DOCKER_TOKEN }}
                acr-account: registry.hub.docker.com
                acr-imagename: dodevops/cloudcontrol-aws:$TAG
        -   name: Push Azure Image
            uses: julioarruda/pushimagetoregistry@v1
            with:
                acr-tokenname: ${{ secrets.DOCKER_USERNAME }}
                acr-token: ${{ secrets.DOCKER_TOKEN }}
                acr-account: registry.hub.docker.com
                acr-imagename: dodevops/cloudcontrol-aws:$TAG
