name: "Build and push"

on:
    push:
        branches:
            - master
    release:
        types:
            - created

jobs:
    build:
        name: Building and pushing containers
        runs-on: ubuntu-latest
        steps:
            -   name: Set tag to latest
                uses: allenevans/set-env@v1.0.0
                with:
                    IMAGE_TAG: latest
                if: github.ref == 'refs/heads/master'
            -   name: Set tag to release
                uses: allenevans/set-env@v1.0.0
                with:
                    IMAGE_TAG: ${{ github.ref }}
                if: github.ref != 'refs/heads/master'
            -   name: Checkout
                uses: actions/checkout@v1
            -   run: bash build.sh ${IMAGE_TAG}
            -   name: Push AWS Image
                uses: julioarruda/pushimagetoregistry@v1
                with:
                    acr-tokenname: ${{ secrets.DOCKER_USERNAME }}
                    acr-token: ${{ secrets.DOCKER_TOKEN }}
                    acr-account: registry.hub.docker.com
                    acr-imagename: dodevops/cloudcontrol-aws:${IMAGE_TAG}
            -   name: Push Azure Image
                uses: julioarruda/pushimagetoregistry@v1
                with:
                    acr-tokenname: ${{ secrets.DOCKER_USERNAME }}
                    acr-token: ${{ secrets.DOCKER_TOKEN }}
                    acr-account: registry.hub.docker.com
                    acr-imagename: dodevops/cloudcontrol-aws:${IMAGE_TAG}
