name: "Build and push"

on:
    push:
        branches:
            - master
    release:
        types:
            - created

jobs:
    build:
        name: Building and pushing containers
        runs-on: ubuntu-latest
        steps:
            -   name: Set tag to latest
                uses: allenevans/set-env@v1.0.0
                with:
                    IMAGE_TAG: latest
                if: github.ref == 'refs/heads/master'
            -   name: Extract release
                id: extract-release
                uses: frabert/replace-string-action@v1.1
                with:
                    pattern: "^refs/tags/(.+)$"
                    string: ${{ github.ref }}
                    replace-with: "$1"
                if: github.ref != 'refs/heads/master'
            -   name: Set tag to release
                uses: allenevans/set-env@v1.0.0
                with:
                    IMAGE_TAG: ${{ steps.extract-release.outputs.replaced }}
                if: github.ref != 'refs/heads/master'
            -   name: Checkout
                uses: actions/checkout@v1
            -   run: "bash build.sh ${IMAGE_TAG}"
            -   name: Push AWS Image
                uses: julioarruda/pushimagetoregistry@v1
                with:
                    acr-tokenname: ${{ secrets.DOCKER_USERNAME }}
                    acr-token: ${{ secrets.DOCKER_TOKEN }}
                    acr-account: docker.io
                    acr-imagename: dodevops/cloudcontrol-aws:${{ env.IMAGE_TAG }}
            -   name: Push Azure Image
                uses: julioarruda/pushimagetoregistry@v1
                with:
                    acr-tokenname: ${{ secrets.DOCKER_USERNAME }}
                    acr-token: ${{ secrets.DOCKER_TOKEN }}
                    acr-account: docker.io
                    acr-imagename: dodevops/cloudcontrol-aws:${{ env.IMAGE_TAG }}
