name: "Update docs"

on:
    push:
        branches-ignore:
            - main
jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Set up Go
                uses: actions/setup-go@v3
                with:
                    go-version: 1.19

            -   name: Update README
                run: |
                    go run cmd/doc/mkdoc.go

            -   name: Add & Commit
                uses: EndBug/add-and-commit@v9.1.1
                with:
                    add: "README.md"
                    author_name: "DO! DevOps bot"
                    author_email: "info@dodevops.io"
                    message: "docs: Automatic docs update"
                    push: true

