name: release

on:
    push:
        branches:
            - 'main'
        tags:
            - 'v*.*.*'
    pull_request:
        branches:
            - 'main'

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   run: |
                    apt-get update >/dev/null && apt-get install -y shellcheck >/dev/null
                    bash check.sh
    build:
        strategy:
            matrix:
                flavour:
                    - name: aws
                      platforms: "linux/amd64,linux/arm64"
                    - name: azure
                      platforms: "linux/amd64"
                    - name: simple
                      platforms: "linux/amd64,linux/arm64"
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Docker meta
                id: meta
                uses: docker/metadata-action@v3
                with:
                    # list of Docker images to use as base name for tags
                    images: |
                        dodevops/cloudcontrol-${{ matrix.flavour.name }}
                    # generate Docker tags based on the following events/attributes
                    tags: |
                        type=ref,event=branch
                        type=ref,event=pr
                        type=semver,pattern={{version}}
                        type=semver,pattern={{major}}.{{minor}}
                        type=semver,pattern={{major}}
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1
            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_TOKEN }}
            -   name: Build
                run: |
                    cat build/Dockerfile.prefix > Dockerfile
                    cat "flavour/${{ matrix.flavour.name }}/Dockerfile.flavour" >> Dockerfile
                    cat build/Dockerfile.suffix >> Dockerfile
            -   name: Clean up Docker
                run: |
                    docker system prune -f --filter "until=5h"
            -   name: Build and push
                id: docker_build
                uses: docker/build-push-action@v2
                with:
                    context: .
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    pull: true
                    no-cache: true
                    platforms:  ${{ matrix.flavour.platforms }}
